name: Brittany P. Boribong
url: boribong.github.io
description: Postdoctoral Research Fellow at Massachusetts General Hospital

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
