name: Brittany P. Boribong
url: boribong.github.io
description: PhD Candidate in Genetics, Bioinformatics, and Computational Biology at Virginia Tech

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
